name: Statistics

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the private repository
        uses: actions/checkout@v4

      - name: Checkout the public repository
        uses: actions/checkout@v4
        with:
          repository: BoBoBaSs84/github-stats
          token: ${{ secrets.REPOSITORIES_TOKEN }}
          path: .private-repo

      - name: Copy those files
        run: |
          cp .private-repo/generated/*.svg ./images/

      - name: Clean up the private repository
        run: |
          rm -rf .private-repo

      - name: Commit the changes to the public repository
        run: |
          git config --global user.name "BoBoBaSs84"
          git config --global user.email "73112377+BoBoBaSs84@users.noreply.github.com"
          git add .
          git commit -m "chore: updated images files" -m "Co-Authored-By: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          git push
